### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by lukee910** [sdorra/angular-dashboard-framework#124] opened 2015-07-21 09:20 UTC
It would be quite nice to be able to translate the tooltips / titles / texts. I already did this in my fork, should I create a pull request that works like that?

My idea was to have an object of strings that you can pass to the dashboard and all texts are read from that object instead of being hard coded (with a default object if nothing is passed).

**Comment by sdorra** [comment] 2015-10-11 14:48
Duplicate of #102

**Closed by sdorra** 2015-10-11 14:48 UTC
Labels: duplicate
